import { catalog,db,fail,sameOrigin,notifyInquiry } from '@/lib/server';
import { inquirySchema } from '@/lib/validation';
export async function POST(req:Request){try{sameOrigin(req);const raw=await req.text();if(raw.length>20000)return fail(new Error('La solicitud es demasiado larga'));const parse=inquirySchema.safeParse(JSON.parse(raw));if(!parse.success)return fail(new Error(parse.error.issues[0].message));const d=parse.data;if(d.website)return fail(new Error('No se ha podido procesar la solicitud'));const {machines,referenceMachines,settings}=await catalog();const knownMachines=[...machines,...referenceMachines.filter(r=>!machines.some(m=>m.id===r.id))];if(d.machineIds.some(id=>!knownMachines.some(m=>m.id===id&&!['Vendida','Retirada'].includes(m.availability))))return fail(new Error('Una máquina ya no está disponible. Actualiza tu selección.'));
 const id='OB-'+d.id;const existing=await db().prepare('SELECT id FROM inquiries WHERE id=?').bind(id).first();if(existing)return Response.json({id,demo:!settings.liveInquiries,notification:'already_saved'});
 const ip=req.headers.get('x-vercel-forwarded-for')?.split(',')[0]?.trim()||'unknown';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip+'|'+new Date().toISOString().slice(0,10)));const ipHash=Array.from(new Uint8Array(digest)).map(n=>n.toString(16).padStart(2,'0')).join('');const since=new Date(Date.now()-3600000).toISOString();const count=await db().prepare('SELECT COUNT(*) AS n FROM inquiries WHERE ip_hash=? AND created>?').bind(ipHash,since).first<{n:number}>();if((count?.n??0)>=5)return fail(new Error('Has enviado varias solicitudes. Espera una hora o utiliza el canal de contacto directo.'),429);
 const {website,...clean}=d;const data={...clean,reference:id,machines:d.machineIds.map(id=>{const m=knownMachines.find(m=>m.id===id)!;return {id,brand:m.brand,model:m.model,condition:m.condition,isDemo:m.isDemo}}),privacyVersion:'2026-09-13',demo:!settings.liveInquiries,notes:''};
 await db().prepare('INSERT INTO inquiries(id,data,status,notification,created,ip_hash) VALUES(?,?,?,?,?,?)').bind(id,JSON.stringify(data),'Nueva','pending',new Date().toISOString(),ipHash).run();
 const notification=settings.liveInquiries?await notifyInquiry(id,data,settings):'demo';try{await db().prepare('UPDATE inquiries SET notification=? WHERE id=?').bind(notification,id).run();}catch{console.error('Notification status update failed');}
 return Response.json({id,demo:!settings.liveInquiries,notification},{status:201,headers:{'Cache-Control':'no-store'}});
 }catch(e){console.error('Inquiry failed',e instanceof Error?e.message:'');return fail(new Error('No hemos podido guardar tu solicitud. Tus datos siguen en el formulario; vuelve a intentarlo.'),503);}}
