'use client';
import Link from 'next/link';
import { useState,useEffect,useMemo } from 'react';
import { ArrowUpRight,ArrowRight,ArrowLeft,Plus,Search,Check,ScanLine,Scale,BadgeCheck } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableBody,TableRow,TableCell,TableHead,TableHeader } from '@/components/ui/table';
import { type Machine,type Settings,categories,partnerBrands,money,comparisonRows } from '@/lib/catalog';
import { whatsappLink } from '@/lib/site';
import { Header } from '@/components/site/header';
import { Footer } from '@/components/site/footer';
import { ProductImage } from '@/components/site/product-image';
import { WhatsAppIcon } from '@/components/site/icons';
import { InquiryDialog,Choice } from '@/components/site/inquiry-dialog';

/** Etiqueta que distingue una unidad usada de un modelo nuevo. */
export function ConditionBadge({m}:{m:Machine}){return m.condition==='Reacondicionada'?<span className="badge badge-used"><BadgeCheck size={14} aria-hidden="true"/> Segunda mano · Revisada</span>:<span className="badge badge-new">Nueva · Bajo propuesta</span>}
const usedPrice=(m:Machine)=>m.price===null?'Consultar':money(m.price);

export default function CompareApp({machines,referenceMachines=[],settings,initialCompare=[]}:{machines:Machine[];referenceMachines?:Machine[];settings:Settings;initialCompare?:string[]}){
 const [selected,setSelected]=useState<string[]>(initialCompare.length?initialCompare:[]),[differences,setDifferences]=useState(false);
 const [ask,setAsk]=useState(false),[askMachines,setAskMachines]=useState<Machine[]>([]),[askSession,setAskSession]=useState(0);
 const [referenceQuery,setReferenceQuery]=useState(''),[referenceCategory,setReferenceCategory]=useState('Todas'),[referenceBrand,setReferenceBrand]=useState('Todas las marcas'),[referenceSlot,setReferenceSlot]=useState(1),[referencePickerOpen,setReferencePickerOpen]=useState(false);
 const allMachines=useMemo(()=>[...machines,...referenceMachines].filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i),[machines,referenceMachines]);
 // Lee la selección guardada en el navegador solo tras montar, para no descuadrar la hidratación.
 // eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect
 useEffect(()=>{try{const raw=initialCompare.length?initialCompare:JSON.parse(sessionStorage.getItem('obrador-comparison')||'[]');const valid=Array.isArray(raw)?raw.filter((id:string)=>allMachines.some(m=>m.id===id)):[];const used=valid.filter((id:string)=>machines.some(m=>m.id===id));setSelected(used.length?[...used,...valid.filter((id:string)=>!used.includes(id))].slice(0,3):[]);}catch{setSelected([]);}},[]);
 function updateSelection(ids:string[]){setSelected(ids);try{sessionStorage.setItem('obrador-comparison',JSON.stringify(ids));}catch{}}
 function chooseReference(m:Machine){if(!baseMachine)return;setReferencePickerOpen(false);const next=[...selected];next[referenceSlot]=m.id;updateSelection([...new Set(next.filter(Boolean))].slice(0,3));requestAnimationFrame(()=>document.getElementById('resultado-comparacion')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));}
 const baseMachine=machines.find(m=>m.id===selected[0]);
 const referenceOptions=useMemo(()=>referenceMachines.filter(m=>(referenceCategory==='Todas'||m.category===referenceCategory)&&(referenceBrand==='Todas las marcas'||m.brand===referenceBrand)&&`${m.brand} ${m.model} ${m.type}`.toLowerCase().includes(referenceQuery.toLowerCase())).sort((a,b)=>Number(b.category===baseMachine?.category)-Number(a.category===baseMachine?.category)),[referenceMachines,referenceCategory,referenceBrand,referenceQuery,baseMachine]);
 function openReferencePicker(slot=1){setReferenceSlot(slot);setReferencePickerOpen(true);}
 function openAsk(ms:Machine[]=[]){setAskMachines(ms);setAskSession(s=>s+1);setAsk(true);}
 useEffect(()=>{const c=(document as unknown as {modelContext?:{registerTool?:(tool:unknown,opts:unknown)=>unknown}}).modelContext;if(!c?.registerTool)return;const lifecycle=new AbortController();const tool={name:'stage_machine_comparison',title:'Preparar comparación de máquinas',description:'Selecciona de dos a tres máquinas existentes y muestra su comparación; no solicita presupuestos.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'},minItems:2,maxItems:3}},required:['ids'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{ids?:unknown})=>{const ids=input?.ids;if(!Array.isArray(ids)||ids.length<2||ids.length>3||new Set(ids).size!==ids.length||ids.some((id:unknown)=>typeof id!=='string'||!allMachines.some(m=>m.id===id)))throw new Error('Selecciona 2 o 3 referencias válidas.');updateSelection(ids);return {selected:ids,action:'comparison_staged'};}};try{Promise.resolve(c.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[allMachines]);
 const compared=selected.map(id=>allMachines.find(m=>m.id===id)).filter(Boolean) as Machine[];
 const wa=(text?:string)=>whatsappLink(settings,text);

 return <><Header settings={settings}/>
 <main id="contenido" className="wrap compare-page"><Link href="/#maquinaria" className="text-link back-link"><ArrowLeft size={16} aria-hidden="true"/> Volver al catálogo</Link><div className="compare-title"><div><div className="eyebrow">ELIGE CON TODA LA INFORMACIÓN</div><h1>Compara antes de decidir.</h1><p>Elige una unidad de segunda mano y busca el modelo nuevo que mejor responda al mismo trabajo.</p></div><label className="switch-label"><Switch checked={differences} onCheckedChange={setDifferences}/> Solo diferencias</label></div><div className="sat-compare-controls"><div className="sat-compare-step"><span className="eyebrow">01 / UNIDAD DE SEGUNDA MANO</span><Select value={selected[0]||'none'} onValueChange={v=>updateSelection(v==='none'?[]:[v,...selected.slice(1).filter(id=>id!==v)])}><SelectTrigger className="compare-picker" aria-label="Unidad de segunda mano"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Selecciona una unidad disponible</SelectItem>{machines.map(m=><SelectItem key={m.id} value={m.id}>{m.brand} {m.model}</SelectItem>)}</SelectContent></Select>{!machines.length&&<p>Aún no hay unidades publicadas. La comparación estará disponible cuando añadamos la primera.</p>}</div><div className="sat-compare-step"><span className="eyebrow">02 / ALTERNATIVA NUEVA</span><button className="reference-select-button" onClick={()=>openReferencePicker(1)}><span>{allMachines.find(m=>m.id===selected[1])?.model||'Buscar máquina nueva'}</span><Search size={18} aria-hidden="true"/></button><p>Explora por marca, función y capacidad. Tú eliges qué comparar.</p></div>{baseMachine&&<button className="text-link sat-third" onClick={()=>openReferencePicker(2)}>{selected[2]?'Cambiar tercera máquina':'+ Añadir otra alternativa'}</button>}</div>
 <Dialog open={referencePickerOpen} onOpenChange={setReferencePickerOpen}><DialogContent className="visual-reference-picker"><DialogTitle>Busca tu alternativa nueva.</DialogTitle><DialogDescription>Fotografías y datos para elegir el modelo que mejor se parece a tu máquina usada.</DialogDescription><section className="new-models-list" id="modelos-nuevos" aria-label="Modelos nuevos"><p className="new-models-description">{baseMachine?`Compara tu ${baseMachine.brand} ${baseMachine.model} con una alternativa nueva.`:'Puedes explorar los modelos nuevos. Selecciona una unidad de segunda mano arriba para compararlos.'}</p><div className="new-models-filters"><div className="search-field"><Search size={18} aria-hidden="true"/><input value={referenceQuery} onChange={e=>setReferenceQuery(e.target.value)} placeholder="Buscar modelo o función" aria-label="Buscar modelo nuevo"/></div><Choice value={referenceBrand} onChange={setReferenceBrand} options={['Todas las marcas',...partnerBrands]} label="Marca del modelo nuevo"/><Choice value={referenceCategory} onChange={setReferenceCategory} options={categories} label="Sector del modelo nuevo"/></div><div className="new-models-scroll">{referenceOptions.map(m=><article className={`new-model-row ${selected.includes(m.id)?'selected-model':''}`} key={m.id}><div className="new-model-photo"><ProductImage m={m} sizes="(max-width: 760px) 45vw, 300px"/></div><div className="new-model-identity"><span className="card-brand">{m.brand}</span><h3>{m.model}</h3><p>{m.type}</p><details><summary>Datos técnicos</summary><p>{m.functioning}</p><p>Potencia: {m.power||'por confirmar'}<br/>Dimensiones: {m.dimensions||'por confirmar'}</p></details></div><div className="new-model-capacity"><span>CAPACIDAD</span><p>{m.capacity||'Según configuración'}</p></div><div className="new-model-price"><span>PRECIO NUEVO · SIN IVA</span><strong>{money(m.price)}</strong></div><button disabled={!baseMachine||(selected.includes(m.id)&&selected[referenceSlot]!==m.id)} className="btn btn-outline" onClick={()=>chooseReference(m)}>{selected.includes(m.id)?<><Check size={16} aria-hidden="true"/> Seleccionado</>:<>Comparar <Plus size={16} aria-hidden="true"/></>}</button></article>)}</div>{!referenceOptions.length&&<div className="empty-state"><p>No hay modelos con estos filtros.</p><button className="text-link" onClick={()=>{setReferenceQuery('');setReferenceBrand('Todas las marcas');setReferenceCategory('Todas')}}>Restablecer filtros</button></div>}<p className="new-models-note">Las máquinas del mismo sector aparecen primero. Revisa función, capacidad y configuración: no todas son equivalentes.</p></section></DialogContent></Dialog>
 {compared.length?<><div className="comparison-scroll" id="resultado-comparacion"><div style={{minWidth:compared.length===3?900:640}}><div className="comparison-cards" style={{gridTemplateColumns:`180px repeat(${compared.length}, minmax(0,1fr))`}}><div className="compare-summary-label"><Scale size={27} aria-hidden="true"/><p>Tu elección,<br/>con perspectiva.</p></div>{compared.map(m=><div key={m.id} className="comparison-card"><ProductImage m={m} sizes="300px"/><span className="card-brand">{m.brand}</span><h2>{m.model}</h2><ConditionBadge m={m}/><strong>{m.condition==='Nueva'?money(m.price):usedPrice(m)}</strong><button className="btn btn-dark" onClick={()=>openAsk([m])}>Prepara mi propuesta <ArrowUpRight size={16} aria-hidden="true"/></button>{m.condition==='Reacondicionada'&&machines.some(x=>x.id===m.id)&&<a href={'/maquina/'+m.id} className="text-link">Ver en detalle <ArrowRight size={15} aria-hidden="true"/></a>}</div>)}</div><Table className="compare-table"><TableHeader><TableRow><TableHead className="sr-only">Característica</TableHead>{compared.map(m=><TableHead className="sr-only" key={m.id}>{m.model} {m.condition}</TableHead>)}</TableRow></TableHeader><TableBody>{comparisonRows(compared).filter(r=>!differences||new Set(r.values).size>1).map(r=><TableRow key={r.label} className={new Set(r.values).size>1?'different':''}><TableCell className="row-label"><small>{r.group}</small>{r.label}</TableCell>{r.values.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table>{differences&&!comparisonRows(compared).some(r=>new Set(r.values).size>1)&&<p className="technical-note">No hay diferencias documentadas entre las referencias seleccionadas.</p>}</div></div><div className="compare-caveat"><ScanLine size={22} aria-hidden="true"/><div><strong>Datos claros, decisiones mejores.</strong><p>Los importes indicados no incluyen IVA, envío ni instalación, salvo que se especifique. Los campos pendientes necesitan confirmación técnica. La vida útil restante no es una garantía de duración.</p></div></div></>:<div className="empty-state"><Scale size={32} aria-hidden="true"/><h2>{machines.length?'Primero, elige una máquina de segunda mano.':'El comparador se activa con la primera unidad publicada.'}</h2>{!machines.length&&<><p>Mientras tanto te ayudamos a comparar opciones sin compromiso.</p><div className="hero-actions">{settings.whatsapp&&<a className="btn btn-wa" href={wa()} target="_blank" rel="noopener"><WhatsAppIcon/> Pregúntanos por WhatsApp</a>}<button className="btn btn-dark" onClick={()=>openAsk()}>Pedir asesoramiento <ArrowUpRight size={17} aria-hidden="true"/></button></div></>}</div>}
 </main>
 <Footer settings={settings}/>
 {askSession>0&&<InquiryDialog key={askSession} open={ask} onOpenChange={setAsk} machines={askMachines} settings={settings}/>}
 </>;
}
