'use client';
import Link from 'next/link';
import { useState,useEffect,useMemo } from 'react';
import Image from 'next/image';
import { ArrowUpRight,ArrowRight,ArrowLeft,Plus,Search,Check,X,ShieldCheck,Truck,ScanLine,Scale,Camera,Wheat,IceCreamBowl,ChefHat,CookingPot,BadgeCheck,Wrench } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableBody,TableRow,TableCell,TableHead,TableHeader } from '@/components/ui/table';
import { Toaster } from 'sonner';
import { type Machine,type Settings,categories,partnerBrands,officialBrands,money,comparisonRows,workshopPhoto } from '@/lib/catalog';
import { whatsappLink } from '@/lib/site';
import { Header } from '@/components/site/header';
import { Footer } from '@/components/site/footer';
import { ProductImage } from '@/components/site/product-image';
import { WhatsAppIcon } from '@/components/site/icons';
import { BrandStrip } from '@/components/site/brand-strip';
import { TrustSection,RevisionChecklist } from '@/components/site/trust';
import { InquiryDialog,Choice } from '@/components/site/inquiry-dialog';
import { TechSheetButton } from '@/components/site/tech-sheet-dialog';

/** Etiqueta que distingue una unidad usada de un modelo nuevo. */
export function ConditionBadge({m}:{m:Machine}){return m.condition==='Reacondicionada'?<span className="badge badge-used"><BadgeCheck size={14} aria-hidden="true"/> Segunda mano · Revisada</span>:<span className="badge badge-new">Nueva · Bajo propuesta</span>}
const usedPrice=(m:Machine)=>m.price===null?'Consultar':money(m.price);

export default function CatalogApp({machines,referenceMachines=[],settings,mode='catalog',initialCompare=[]}:{machines:Machine[];referenceMachines?:Machine[];settings:Settings;mode?:'catalog'|'compare';initialCompare?:string[]}){
 const [selectedBrand,setSelectedBrand]=useState('Todas las marcas');
 const [category,setCategory]=useState('Todas'),[query,setQuery]=useState(''),[sort,setSort]=useState('Más recientes');
 const [selected,setSelected]=useState<string[]>(initialCompare.length?initialCompare:[]),[differences,setDifferences]=useState(false);
 const [ask,setAsk]=useState(false),[askMachines,setAskMachines]=useState<Machine[]>([]),[askSession,setAskSession]=useState(0);
 const [referenceQuery,setReferenceQuery]=useState(''),[referenceCategory,setReferenceCategory]=useState('Todas'),[referenceBrand,setReferenceBrand]=useState('Todas las marcas'),[referenceSlot,setReferenceSlot]=useState(1),[referencePickerOpen,setReferencePickerOpen]=useState(false);
 const allMachines=useMemo(()=>[...machines,...referenceMachines].filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i),[machines,referenceMachines]);
 // Lee la selección guardada en el navegador solo tras montar, para no descuadrar la hidratación.
 // eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect
 useEffect(()=>{try{const raw=initialCompare.length?initialCompare:JSON.parse(sessionStorage.getItem('obrador-comparison')||'[]');const valid=Array.isArray(raw)?raw.filter((id:string)=>allMachines.some(m=>m.id===id)):[];const used=valid.filter((id:string)=>machines.some(m=>m.id===id));setSelected(used.length?[...used,...valid.filter((id:string)=>!used.includes(id))].slice(0,3):[]);}catch{setSelected([]);}},[]);
 function updateSelection(ids:string[]){setSelected(ids);try{sessionStorage.setItem('obrador-comparison',JSON.stringify(ids));}catch{}}
 function startComparison(m:Machine){updateSelection([m.id]);window.location.assign('/comparar?ids='+encodeURIComponent(m.id));}
 function chooseReference(m:Machine){if(!baseMachine)return;setReferencePickerOpen(false);const next=[...selected];next[referenceSlot]=m.id;updateSelection([...new Set(next.filter(Boolean))].slice(0,3));requestAnimationFrame(()=>document.getElementById('resultado-comparacion')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));}
 const baseMachine=machines.find(m=>m.id===selected[0]);
 const referenceOptions=useMemo(()=>referenceMachines.filter(m=>(referenceCategory==='Todas'||m.category===referenceCategory)&&(referenceBrand==='Todas las marcas'||m.brand===referenceBrand)&&`${m.brand} ${m.model} ${m.type}`.toLowerCase().includes(referenceQuery.toLowerCase())).sort((a,b)=>Number(b.category===baseMachine?.category)-Number(a.category===baseMachine?.category)),[referenceMachines,referenceCategory,referenceBrand,referenceQuery,baseMachine]);
 function openReferencePicker(slot=1){setReferenceSlot(slot);setReferencePickerOpen(true);}
 function openAsk(ms:Machine[]=[]){setAskMachines(ms);setAskSession(s=>s+1);setAsk(true);}
 useEffect(()=>{const c=(document as unknown as {modelContext?:{registerTool?:(tool:unknown,opts:unknown)=>unknown}}).modelContext;if(!c?.registerTool)return;const lifecycle=new AbortController();const tool={name:'stage_machine_comparison',title:'Preparar comparación de máquinas',description:'Selecciona de dos a tres máquinas existentes y muestra su comparación; no solicita presupuestos.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'},minItems:2,maxItems:3}},required:['ids'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{ids?:unknown})=>{const ids=input?.ids;if(!Array.isArray(ids)||ids.length<2||ids.length>3||new Set(ids).size!==ids.length||ids.some((id:unknown)=>typeof id!=='string'||!allMachines.some(m=>m.id===id)))throw new Error('Selecciona 2 o 3 referencias válidas.');updateSelection(ids);if(mode!=='compare')window.location.assign('/comparar?ids='+ids.map(encodeURIComponent).join(','));return {selected:ids,action:'comparison_staged'};}};try{Promise.resolve(c.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[allMachines,mode]);
 const filtered=useMemo(()=>{let a=machines.filter(m=>(selectedBrand==='Todas las marcas'||m.brand===selectedBrand)&&(category==='Todas'||m.category===category)&&`${m.brand} ${m.model} ${m.type}`.toLowerCase().includes(query.toLowerCase()));if(sort==='Precio: menor primero')a=[...a].sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));if(sort==='Nombre: A–Z')a=[...a].sort((a,b)=>a.model.localeCompare(b.model));return a;},[machines,category,query,sort,selectedBrand]);
 const compared=selected.map(id=>allMachines.find(m=>m.id===id)).filter(Boolean) as Machine[];
 // Sin stock publicado, la portada enseña los modelos nuevos de referencia con los mismos filtros.
 const showcase=useMemo(()=>machines.length?[]:referenceMachines.filter(m=>(category==='Todas'||m.category===category)&&`${m.brand} ${m.model} ${m.type}`.toLowerCase().includes(query.toLowerCase())),[machines,referenceMachines,category,query]);
 const iconCategories=[null,Wheat,IceCreamBowl,ChefHat,CookingPot];
 const wa=(text?:string)=>whatsappLink(settings,text);

 return <><Toaster position="bottom-left"/><Header settings={settings} active={mode==='compare'?'compare':'catalog'}/>
 {mode==='catalog'&&<main id="contenido">
 <section className="sat-intro wrap">
  <div>
   <span className="eyebrow">MAQUINARIA DE OBRADOR · REVISADA EN TALLER</span>
   <h1>El oficio sigue.<br/><em>La máquina<br/>también.</em></h1>
   <div className="official-service">
    <span className="official-service-label"><BadgeCheck size={18} aria-hidden="true"/> Servicio técnico oficial de</span>
    <ul aria-label="Marcas de las que somos servicio técnico oficial">{officialBrands.map(b=><li key={b}>{b}</li>)}</ul>
   </div>
   <p>Maquinaria de segunda mano para panadería, pastelería, heladería y hostelería. <strong>Cada máquina se revisa en nuestro taller antes de venderse y sale con garantía por escrito.</strong></p>
   <div className="hero-actions">
    <a className="btn btn-dark" href="#catalogo">Ver máquinas <ArrowRight size={18} aria-hidden="true"/></a>
    {settings.whatsapp&&<a className="btn btn-wa" href={wa()} target="_blank" rel="noopener"><WhatsAppIcon/> Escríbenos por WhatsApp</a>}
    <a className="text-link" href="/servicio-tecnico">Servicio técnico y mantenimiento <ArrowUpRight size={17} aria-hidden="true"/></a>
   </div>
   <div className="vintage-caption-line"><span>REVISAR / REPARAR / GARANTIZAR</span><span>EMAPAN · DESDE {settings.foundedYear}</span></div>
  </div>
  <figure className="archive-poster workshop-photo">
   <div className="archive-poster-label"><span>NUESTRO TALLER</span><span>{settings.locality.toUpperCase()} · {settings.region.toUpperCase()}</span></div>
   <div className="archive-poster-frame">
    {workshopPhoto.src?<Image src={workshopPhoto.src} alt={workshopPhoto.alt} width={700} height={880} sizes="(max-width: 760px) 90vw, 350px" priority/>:<div className="photo-placeholder" role="img" aria-label="Espacio reservado para una foto real del taller"><Camera size={34} aria-hidden="true"/><strong>[PENDIENTE: foto real del taller o del equipo]</strong><span>Formato vertical, mínimo 700 × 880 px</span></div>}
   </div>
   <figcaption>El equipo de Emapan revisa y prueba cada máquina en su taller de {settings.locality} antes de venderla.</figcaption>
  </figure>
 </section>
 <div className="benefit-bar wrap"><span><Wrench size={18} aria-hidden="true"/> Revisada en nuestro taller</span><span><ShieldCheck size={18} aria-hidden="true"/> Garantía por escrito</span><span><Truck size={18} aria-hidden="true"/> Envíos a toda España</span><span><Scale size={18} aria-hidden="true"/> Comparación con nueva</span></div>
 <BrandStrip/>
 <section className="catalog wrap" id="catalogo" aria-labelledby="catalogo-titulo"><div className="section-title"><div><div className="eyebrow">UNIDADES CON UNA SEGUNDA VIDA</div><h2 id="catalogo-titulo">Máquinas disponibles.</h2></div><span className="result-count" aria-live="polite">{machines.length?`${filtered.length} ${filtered.length===1?'unidad':'unidades'}`:`${showcase.length} modelos nuevos`}</span></div>
 {machines.length>0&&<div className="brands-panel"><div className="brands-heading"><span>Marcas disponibles en segunda mano</span>{selectedBrand!=='Todas las marcas'&&<button onClick={()=>setSelectedBrand('Todas las marcas')} className="clear-brand">Ver todas <X size={13} aria-hidden="true"/></button>}</div><div className="brand-selector" role="group" aria-label="Filtrar por marca">{[...new Set(machines.map(m=>m.brand))].map(b=><button key={b} className={selectedBrand===b?'selected':''} onClick={()=>setSelectedBrand(selectedBrand===b?'Todas las marcas':b)} aria-pressed={selectedBrand===b}>{b}</button>)}</div></div>}
 <div className="category-row" role="group" aria-label="Filtrar por sector">{categories.map((c,i)=>{const Icon=iconCategories[i];return <button className={`category-pill ${category===c?'chosen':''}`} key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}>{Icon&&<Icon size={17} aria-hidden="true"/>} {c}</button>})}</div>
 <div className="filter-row"><div className="search-field"><Search size={18} aria-hidden="true"/><input aria-label="Buscar maquinaria" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca una máquina, marca o modelo"/>{query&&<button onClick={()=>setQuery('')} aria-label="Borrar búsqueda"><X size={16}/></button>}</div>{machines.length>0&&<Choice value={sort} onChange={setSort} options={['Más recientes','Precio: menor primero','Nombre: A–Z']} label="Ordenar catálogo"/>}</div>
 <div className="machine-grid">{filtered.map(m=><article className="machine-card" key={m.id}><div className="card-visual"><ConditionBadge m={m}/><button className="add-compare" onClick={()=>startComparison(m)} aria-label={`Comparar ${m.brand} ${m.model} con una nueva`}><Scale size={18} aria-hidden="true"/><span>Comparar</span></button><a href={'/maquina/'+m.id} className="machine-image" tabIndex={-1} aria-hidden="true"><ProductImage m={m}/></a><span className={`image-caption availability-${m.availability.toLowerCase()}`}>{m.availability.toUpperCase()}</span></div><div className="card-copy"><span className="card-brand">{m.brand}</span><a href={'/maquina/'+m.id}><h3>{m.model}</h3></a><p>{m.type}</p><div className="card-meta"><span>{m.category}</span>{m.year&&<span>Año {m.year}</span>}</div><div className="card-bottom"><div><span className="price-label">{m.price===null?'PRECIO':'PRECIO SIN IVA'}</span><strong>{usedPrice(m)}</strong></div><a href={'/maquina/'+m.id} className="circle-button" aria-label={`Ver ficha de ${m.brand} ${m.model}`}><ArrowUpRight size={22} aria-hidden="true"/></a></div>{settings.whatsapp&&<a className="btn btn-wa card-wa" href={wa(`Hola, vengo de la web y me interesa la ${m.brand} ${m.model}${m.year?` (${m.year})`:''}.`)} target="_blank" rel="noopener"><WhatsAppIcon/> Preguntar por WhatsApp</a>}</div></article>)}</div>
 {!machines.length&&<><div className="stock-soon"><span className="stock-soon-dot" aria-hidden="true"/><div><strong>Las primeras unidades de segunda mano están en camino.</strong><p>Mientras tanto, explora los modelos nuevos que ofrecemos bajo propuesta o cuéntanos qué máquina buscas y la localizamos por ti.</p></div><div className="stock-soon-actions">{settings.whatsapp&&<a className="btn btn-wa" href={wa('Hola, vengo de la web y busco una máquina de segunda mano.')} target="_blank" rel="noopener"><WhatsAppIcon/> Dinos qué buscas</a>}<button className="btn btn-dark" onClick={()=>openAsk()}>Busquemos tu máquina <ArrowRight size={17} aria-hidden="true"/></button></div></div>
 <div className="reference-rail">{showcase.map(m=><article className="ref-card" key={m.id}><div className="ref-card-visual"><ConditionBadge m={m}/><ProductImage m={m}/></div><div className="ref-card-copy"><span className="card-brand">{m.brand}</span><h3>{m.model}</h3><p>{m.type}</p><div className="card-meta"><span>{m.category}</span>{m.capacity&&<span>{m.capacity}</span>}</div><div className="ref-card-actions"><TechSheetButton m={m} settings={settings} onAsk={x=>openAsk([x])}/><button className="btn btn-dark" onClick={()=>openAsk([m])}>Pedir propuesta</button></div></div></article>)}</div>
 {!showcase.length&&<div className="empty-state"><Search size={30} aria-hidden="true"/><h3>No hay modelos con esa búsqueda.</h3><button className="text-link" onClick={()=>{setQuery('');setCategory('Todas')}}>Limpiar filtros</button></div>}</>}
 {machines.length>0&&!filtered.length&&<div className="empty-state"><Search size={30} aria-hidden="true"/><h3>No encontramos esa máquina.</h3><p>Prueba otra búsqueda o cuéntanos qué necesitas.</p><button className="btn btn-dark" onClick={()=>openAsk()}>Busquemos tu máquina <ArrowRight size={17} aria-hidden="true"/></button><button className="text-link" onClick={()=>{setQuery('');setCategory('Todas');setSelectedBrand('Todas las marcas')}}>Limpiar filtros</button></div>}
 </section>
 <TrustSection settings={settings}/>
 <RevisionChecklist/>
 <section className="sell-band wrap"><div><span className="eyebrow">¿TIENES UNA MÁQUINA PARADA?</span><h2>También puedes vender con nosotros.</h2><p>Envíanos fotos y estado. Podemos encontrar comprador a comisión, guardarla en nuestro almacén o hacerte una oferta de compra directa.</p></div><a className="btn btn-white" href="/vender">Solicitar valoración <ArrowUpRight size={18} aria-hidden="true"/></a></section>
 <section className="archive-workshop wrap"><figure><Image src="/images/bakery-interior-1900.jpg" alt="Fotografía histórica en blanco y negro de un panadero junto a sus panes y el horno de un obrador, a comienzos del siglo XX" width={2000} height={1537} sizes="(max-width: 760px) 92vw, 620px"/><figcaption>«Interior of a bakery», principios del siglo XX. Manitoulin Island (Canadá). Archives of Ontario, dominio público.</figcaption></figure><div><span className="eyebrow">UN OFICIO QUE CONTINÚA</span><h2>Cambian las máquinas.<br/>Permanece el oficio.</h2><p>Cada obrador tiene su ritmo. Elegir una máquina de segunda mano empieza por conocer su estado, su capacidad y el trabajo que va a hacer.</p><p>En Emapan concretamos contigo la revisión, el transporte y las condiciones de la propuesta.</p><button className="text-link" onClick={()=>openAsk()}>Hablemos de tu obrador <ArrowUpRight size={17} aria-hidden="true"/></button></div></section>
 <section className="proposal-section wrap"><div><span className="eyebrow">DE LA MÁQUINA A TU OBRADOR</span><h2>Una propuesta.<br/>Todo lo que necesitas saber.</h2></div><div className="proposal-steps"><div><span>01</span><h3>Cuéntanos tu proyecto</h3><p>Qué produces, cuánto espacio tienes y dónde trabajas.</p></div><div><span>02</span><h3>Afinamos la elección</h3><p>Revisamos configuración, estado y necesidades técnicas.</p></div><div><span>03</span><h3>Recibe tu propuesta</h3><p>Precio, transporte, plazo y garantía, concretados por escrito.</p></div><button className="text-link" onClick={()=>openAsk()}>Prepara mi propuesta <ArrowUpRight size={19} aria-hidden="true"/></button></div></section>
 </main>}
 {mode==='compare'&&<main id="contenido" className="wrap compare-page"><Link href="/#catalogo" className="text-link back-link"><ArrowLeft size={16} aria-hidden="true"/> Volver al catálogo</Link><div className="compare-title"><div><div className="eyebrow">ELIGE CON TODA LA INFORMACIÓN</div><h1>Compara antes de decidir.</h1><p>Elige una unidad de segunda mano y busca el modelo nuevo que mejor responda al mismo trabajo.</p></div><label className="switch-label"><Switch checked={differences} onCheckedChange={setDifferences}/> Solo diferencias</label></div><div className="sat-compare-controls"><div className="sat-compare-step"><span className="eyebrow">01 / UNIDAD DE SEGUNDA MANO</span><Select value={selected[0]||'none'} onValueChange={v=>updateSelection(v==='none'?[]:[v,...selected.slice(1).filter(id=>id!==v)])}><SelectTrigger className="compare-picker" aria-label="Unidad de segunda mano"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Selecciona una unidad disponible</SelectItem>{machines.map(m=><SelectItem key={m.id} value={m.id}>{m.brand} {m.model}</SelectItem>)}</SelectContent></Select>{!machines.length&&<p>Aún no hay unidades publicadas. La comparación estará disponible cuando añadamos la primera.</p>}</div><div className="sat-compare-step"><span className="eyebrow">02 / ALTERNATIVA NUEVA</span><button className="reference-select-button" onClick={()=>openReferencePicker(1)}><span>{allMachines.find(m=>m.id===selected[1])?.model||'Buscar máquina nueva'}</span><Search size={18} aria-hidden="true"/></button><p>Explora por marca, función y capacidad. Tú eliges qué comparar.</p></div>{baseMachine&&<button className="text-link sat-third" onClick={()=>openReferencePicker(2)}>{selected[2]?'Cambiar tercera máquina':'+ Añadir otra alternativa'}</button>}</div>
 <Dialog open={referencePickerOpen} onOpenChange={setReferencePickerOpen}><DialogContent className="visual-reference-picker"><DialogTitle>Busca tu alternativa nueva.</DialogTitle><DialogDescription>Fotografías y datos para elegir el modelo que mejor se parece a tu máquina usada.</DialogDescription><section className="new-models-list" id="modelos-nuevos" aria-label="Modelos nuevos"><p className="new-models-description">{baseMachine?`Compara tu ${baseMachine.brand} ${baseMachine.model} con una alternativa nueva.`:'Puedes explorar los modelos nuevos. Selecciona una unidad de segunda mano arriba para compararlos.'}</p><div className="new-models-filters"><div className="search-field"><Search size={18} aria-hidden="true"/><input value={referenceQuery} onChange={e=>setReferenceQuery(e.target.value)} placeholder="Buscar modelo o función" aria-label="Buscar modelo nuevo"/></div><Choice value={referenceBrand} onChange={setReferenceBrand} options={['Todas las marcas',...partnerBrands]} label="Marca del modelo nuevo"/><Choice value={referenceCategory} onChange={setReferenceCategory} options={categories} label="Sector del modelo nuevo"/></div><div className="new-models-scroll">{referenceOptions.map(m=><article className={`new-model-row ${selected.includes(m.id)?'selected-model':''}`} key={m.id}><div className="new-model-photo"><ProductImage m={m} sizes="(max-width: 760px) 45vw, 300px"/></div><div className="new-model-identity"><span className="card-brand">{m.brand}</span><h3>{m.model}</h3><p>{m.type}</p><details><summary>Datos técnicos</summary><p>{m.functioning}</p><p>Potencia: {m.power||'por confirmar'}<br/>Dimensiones: {m.dimensions||'por confirmar'}</p></details></div><div className="new-model-capacity"><span>CAPACIDAD</span><p>{m.capacity||'Según configuración'}</p></div><div className="new-model-price"><span>PRECIO NUEVO · SIN IVA</span><strong>{money(m.price)}</strong></div><button disabled={!baseMachine||(selected.includes(m.id)&&selected[referenceSlot]!==m.id)} className="btn btn-outline" onClick={()=>chooseReference(m)}>{selected.includes(m.id)?<><Check size={16} aria-hidden="true"/> Seleccionado</>:<>Comparar <Plus size={16} aria-hidden="true"/></>}</button></article>)}</div>{!referenceOptions.length&&<div className="empty-state"><p>No hay modelos con estos filtros.</p><button className="text-link" onClick={()=>{setReferenceQuery('');setReferenceBrand('Todas las marcas');setReferenceCategory('Todas')}}>Restablecer filtros</button></div>}<p className="new-models-note">Las máquinas del mismo sector aparecen primero. Revisa función, capacidad y configuración: no todas son equivalentes.</p></section></DialogContent></Dialog>
 {compared.length?<><div className="comparison-scroll" id="resultado-comparacion"><div style={{minWidth:compared.length===3?900:640}}><div className="comparison-cards" style={{gridTemplateColumns:`180px repeat(${compared.length}, minmax(0,1fr))`}}><div className="compare-summary-label"><Scale size={27} aria-hidden="true"/><p>Tu elección,<br/>con perspectiva.</p></div>{compared.map(m=><div key={m.id} className="comparison-card"><ProductImage m={m} sizes="300px"/><span className="card-brand">{m.brand}</span><h2>{m.model}</h2><ConditionBadge m={m}/><strong>{m.condition==='Nueva'?money(m.price):usedPrice(m)}</strong><button className="btn btn-dark" onClick={()=>openAsk([m])}>Prepara mi propuesta <ArrowUpRight size={16} aria-hidden="true"/></button>{m.condition==='Reacondicionada'&&machines.some(x=>x.id===m.id)&&<a href={'/maquina/'+m.id} className="text-link">Ver en detalle <ArrowRight size={15} aria-hidden="true"/></a>}</div>)}</div><Table className="compare-table"><TableHeader><TableRow><TableHead className="sr-only">Característica</TableHead>{compared.map(m=><TableHead className="sr-only" key={m.id}>{m.model} {m.condition}</TableHead>)}</TableRow></TableHeader><TableBody>{comparisonRows(compared).filter(r=>!differences||new Set(r.values).size>1).map(r=><TableRow key={r.label} className={new Set(r.values).size>1?'different':''}><TableCell className="row-label"><small>{r.group}</small>{r.label}</TableCell>{r.values.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table>{differences&&!comparisonRows(compared).some(r=>new Set(r.values).size>1)&&<p className="technical-note">No hay diferencias documentadas entre las referencias seleccionadas.</p>}</div></div><div className="compare-caveat"><ScanLine size={22} aria-hidden="true"/><div><strong>Datos claros, decisiones mejores.</strong><p>Los importes indicados no incluyen IVA, envío ni instalación, salvo que se especifique. Los campos pendientes necesitan confirmación técnica. La vida útil restante no es una garantía de duración.</p></div></div></>:<div className="empty-state"><Scale size={32} aria-hidden="true"/><h2>{machines.length?'Primero, elige una máquina de segunda mano.':'El comparador se activa con la primera unidad publicada.'}</h2>{!machines.length&&<><p>Mientras tanto te ayudamos a comparar opciones sin compromiso.</p><div className="hero-actions">{settings.whatsapp&&<a className="btn btn-wa" href={wa()} target="_blank" rel="noopener"><WhatsAppIcon/> Pregúntanos por WhatsApp</a>}<button className="btn btn-dark" onClick={()=>openAsk()}>Pedir asesoramiento <ArrowUpRight size={17} aria-hidden="true"/></button></div></>}</div>}
 </main>}
 <Footer settings={settings}/>
 {askSession>0&&<InquiryDialog key={askSession} open={ask} onOpenChange={setAsk} machines={askMachines} settings={settings}/>}
 </>;
}
