import { partnerBrands,machineComparisonKey,normalizeComparisonKey } from '@/lib/catalog';
import { catalog,db,fail,owner,sameOrigin,getSettings,runtime,notifyInquiry,whatsappReady } from '@/lib/server';
import { machineSchema,settingsSchema } from '@/lib/validation';
export async function GET(){try{await owner();const data=await catalog(true);const [inquiryRows,offerRows]=await Promise.all([db().prepare('SELECT id,data,status,notification,created FROM inquiries ORDER BY created DESC LIMIT 300').all(),db().prepare('SELECT id,data,status,notification,created FROM machine_offers ORDER BY created DESC LIMIT 300').all()]);const e=runtime();return Response.json({...data,inquiries:inquiryRows.results.map((r:any)=>({...r,data:JSON.parse(r.data)})),machineOffers:offerRows.results.map((r:any)=>({...r,data:JSON.parse(r.data)})),emailReady:!!(e.RESEND_API_KEY&&e.FROM_EMAIL),whatsappReady:whatsappReady()},{headers:{'Cache-Control':'no-store'}});}catch{return fail(new Error('No se puede acceder a la gestión'),403);}}
export async function POST(req:Request){try{sameOrigin(req);await owner();const raw=await req.text();if(raw.length>70000)return fail(new Error('Contenido demasiado largo'));const body=JSON.parse(raw);if(body.action==='machine'){const p=machineSchema.safeParse(body.machine);if(!p.success)return fail(new Error(p.error.issues[0].message));const m=p.data;if(m.condition==='Nueva'&&!partnerBrands.some(b=>b.toLowerCase()===m.brand.toLowerCase()))return fail(new Error('Las referencias nuevas deben pertenecer a una de nuestras marcas. Las usadas pueden ser de cualquier marca.'));if(m.condition==='Reacondicionada'&&m.comparisonKey){const {referenceMachines}=await catalog(true);if(!referenceMachines.some(ref=>machineComparisonKey(ref)===normalizeComparisonKey(m.comparisonKey||'')))return fail(new Error('Selecciona una referencia nueva válida para la comparación.'));}await db().prepare('INSERT INTO machines(id,data,published,updated) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,published=excluded.published,updated=excluded.updated').bind(m.id,JSON.stringify(m),m.published?1:0,new Date().toISOString()).run();return Response.json({ok:true});}
 if(body.action==='settings'){const p=settingsSchema.safeParse(body.settings);if(!p.success)return fail(new Error(p.error.issues[0].message));if(p.data.liveInquiries&&!p.data.whatsapp&&!(runtime().RESEND_API_KEY&&runtime().FROM_EMAIL))return fail(new Error('Configura WhatsApp o el servicio de correo antes de activar las consultas reales.'));await db().prepare('INSERT INTO settings(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(JSON.stringify(p.data)).run();return Response.json({ok:true});}
 if(body.action==='lead'){if(!['Nueva','Contactada','Cualificada','Presupuestada','Ganada','Perdida'].includes(body.status))return fail(new Error('Estado no válido'));const row=await db().prepare('SELECT data FROM inquiries WHERE id=?').bind(String(body.id)).first<{data:string}>();if(!row)return fail(new Error('Solicitud no encontrada'),404);const data={...JSON.parse(row.data),notes:String(body.notes||'').slice(0,4000)};await db().prepare('UPDATE inquiries SET status=?,data=? WHERE id=?').bind(body.status,JSON.stringify(data),body.id).run();return Response.json({ok:true});}
 if(body.action==='offer'){if(!['Nueva','Contactada','Valorando','Oferta enviada','Aceptada','Descartada'].includes(body.status))return fail(new Error('Estado no válido'));const row=await db().prepare('SELECT data FROM machine_offers WHERE id=?').bind(String(body.id)).first<{data:string}>();if(!row)return fail(new Error('Valoración no encontrada'),404);const data={...JSON.parse(row.data),notes:String(body.notes||'').slice(0,4000)};await db().prepare('UPDATE machine_offers SET status=?,data=? WHERE id=?').bind(body.status,JSON.stringify(data),body.id).run();return Response.json({ok:true});}
 if(body.action==='retry'){const row=await db().prepare('SELECT data,notification FROM inquiries WHERE id=?').bind(String(body.id)).first<{data:string;notification:string}>();if(!row)return fail(new Error('Solicitud no encontrada'));const data=JSON.parse(row.data);if(data.demo)return fail(new Error('Las pruebas no generan avisos externos.'));if(row.notification==='sent')return Response.json({ok:true});const state=await notifyInquiry(String(body.id),data,await getSettings());await db().prepare('UPDATE inquiries SET notification=? WHERE id=?').bind(state,body.id).run();if(state!=='sent')return fail(new Error('El aviso sigue pendiente. Revisa la configuración del correo y de WhatsApp.'));return Response.json({ok:true});}
 return fail(new Error('Acción no válida'));}catch(e){console.error('Admin operation failed',e instanceof Error?e.message:'');return fail(new Error('No se ha podido guardar. Comprueba tu acceso y vuelve a intentarlo.'),400);}}
